import Akimg from "../../media/images/elite_build.avif";
import playside from "../../media/images/playside.avif";
import playside1 from "../../media/images/playside1.avif";
import playside2 from "../../media/images/playside2.avif";
import playside3 from "../../media/images/playside3.avif";
import playside4 from "../../media/images/playside4.avif";
import playside5 from "../../media/images/playside5.avif";
import playside6 from "../../media/images/playside6.avif";

import Knife1 from "../../media/KnifeImages/knife1.avif";
import Knife2 from "../../media/KnifeImages/knife2.avif";
import Knife3 from "../../media/KnifeImages/knife3.avif";
import Knife4 from "../../media/KnifeImages/knife4.avif";
import Knife5 from "../../media/KnifeImages/knife5.avif";
import Knife6 from "../../media/KnifeImages/knife6.avif";
import Knife7 from "../../media/KnifeImages/knife7.avif";
import Knife8 from "../../media/KnifeImages/knife8.avif";

import Sniper1 from "../../media/SniperImages/sniper1.avif";
import Sniper2 from "../../media/SniperImages/sniper2.avif";
import Sniper3 from "../../media/SniperImages/sniper3.avif";
import Sniper4 from "../../media/SniperImages/sniper4.avif";
import Sniper5 from "../../media/SniperImages/sniper5.avif";
import Sniper6 from "../../media/SniperImages/sniper6.avif";
import Sniper7 from "../../media/SniperImages/sniper7.avif";
import Sniper8 from "../../media/SniperImages/sniper8.avif";

import Gloves1 from "../../media/GlovesImages/gloves1.avif";
import Gloves2 from "../../media/GlovesImages/gloves2.avif";
import Gloves3 from "../../media/GlovesImages/gloves3.avif";
import Gloves4 from "../../media/GlovesImages/gloves4.avif";
import Gloves5 from "../../media/GlovesImages/gloves5.avif";
import Gloves6 from "../../media/GlovesImages/gloves6.avif";
import Gloves7 from "../../media/GlovesImages/gloves7.avif";
import Gloves8 from "../../media/GlovesImages/gloves8.avif";

import ArticleImg from "../../media/images/article.png";
import ArticleImg2 from "../../media/images/article2.png";
import ArticleImg3 from "../../media/images/article3.png";
export const skins = [
   {
      id: "ak47-redline-ft",
      name: "Redline",
      weapon: "AK-47",
      category: "rifle",
      rarity: "classified",
      condition: "FT",
      price: 12.5,
      originalPrice: 18.0,
      discount: 30,
      float: 0.24,
      stattrak: false,
      rating: 1,
      description:
         "The AK-47 Redline features a dark, battle-worn design with red accents across the body.",
      tags: ["featured", "on-sale"],
      inStock: true,
      image: playside6,
   },
   {
      id: "awp-asiimov-fn",
      name: "Asiimov",
      weapon: "AWP",
      category: "sniper",
      rarity: "covert",
      condition: "FN",
      price: 89.0,
      originalPrice: 110.0,
      discount: 19,
      float: 0.08,
      stattrak: true,
      rating: 4.8,
      description:
         "The AWP Asiimov features a futuristic design with bold orange and white accents on a dark body.",
      tags: ["featured", "on-sale", "popular"],
      inStock: true,
      image: playside,
   },
   {
      id: "m4a4-howl-fn",
      name: "Howl",
      weapon: "M4A4",
      category: "rifle",
      rarity: "contraband",
      condition: "FN",
      price: 320.0,
      originalPrice: 320.0,
      discount: 0,
      float: 0.021,
      stattrak: false,
      rating: 5.0,
      description:
         "The rarest skin in CS2 — removed from cases in 2014 after a DMCA claim. Only available through trades.",
      tags: ["featured", "popular", "skin-of-the-week"],
      inStock: true,
      image: playside1,
   },
   {
      id: "glock18-fade-fn",
      name: "Fade",
      weapon: "Glock-18",
      category: "pistol",
      rarity: "restricted",
      condition: "FN",
      price: 55.0,
      originalPrice: 70.0,
      discount: 21,
      float: 0.02,
      stattrak: false,
      rating: 4.5,
      description:
         "A clean fade from purple to yellow across the entire slide, one of the most sought-after Glock skins.",
      tags: ["on-sale", "popular"],
      inStock: true,
      image: playside2,
   },
   {
      id: "deagle-blaze-fn",
      name: "Blaze",
      weapon: "Desert Eagle",
      category: "pistol",
      rarity: "restricted",
      condition: "FT",
      price: 42.0,
      originalPrice: 60.0,
      discount: 30,
      float: 0.19,
      stattrak: false,
      rating: 4.1,
      description:
         "The Desert Eagle Blaze sports a fiery orange flame pattern across a dark body.",
      tags: ["on-sale"],
      inStock: true,
      image: playside3,
   },
   {
      id: "usps-killconfirmed-bs",
      name: "Kill Confirmed",
      weapon: "USP-S",
      category: "pistol",
      rarity: "milspec",
      condition: "BS",
      price: 18.0,
      originalPrice: 25.0,
      discount: 28,
      float: 0.52,
      stattrak: true,
      rating: 3.8,
      description:
         "A bold skull design with a dark military aesthetic. One of the most iconic USP-S skins.",
      tags: ["on-sale"],
      inStock: true,
      image: playside4,
   },
   {
      id: "karambit-doppler-fn",
      name: "Doppler Phase 4",
      weapon: "Karambit",
      category: "knife",
      rarity: "contraband",
      condition: "FN",
      price: 640.0,
      originalPrice: 640.0,
      discount: 0,
      float: 0.014,
      stattrak: false,
      rating: 4.9,
      description:
         "The Karambit Doppler Phase 4 features a deep black and pink swirling pattern — one of the rarest knife finishes.",
      tags: ["featured", "popular"],
      inStock: true,
      image: playside5,
   },
   {
      id: "m4a1s-hyperbeast-ft",
      name: "Hyper Beast",
      weapon: "M4A1-S",
      category: "rifle",
      rarity: "covert",
      condition: "FT",
      price: 32.0,
      originalPrice: 45.0,
      discount: 29,
      float: 0.21,
      stattrak: false,
      rating: 4.3,
      description:
         "A vivid monster illustration splashed across the rifle in pinks, purples and greens.",
      tags: ["on-sale", "new"],
      inStock: true,
      image: playside6,
   },
   {
      id: "awp-lightning-strike-fn",
      name: "Lightning Strike",
      weapon: "AWP",
      category: "sniper",
      rarity: "covert",
      condition: "FN",
      price: 220.0,
      originalPrice: 220.0,
      discount: 0,
      float: 0.04,
      stattrak: false,
      rating: 4.6,
      description:
         "Electric yellow lightning bolts streak across a white canvas. Clean and iconic.",
      tags: ["popular"],
      inStock: true,
   },
   {
      id: "ak47-wild-lotus-fn",
      name: "Wild Lotus",
      weapon: "AK-47",
      category: "rifle",
      rarity: "covert",
      condition: "FN",
      price: 540.0,
      originalPrice: 540.0,
      discount: 0,
      float: 0.06,
      stattrak: true,
      rating: 4.7,
      description:
         "Hand-painted lotus flowers on a soft sage-green body. One of the rarest AK-47 skins ever made.",
      tags: ["popular", "new"],
      inStock: true,
   },
   {
      id: "m4a4-neo-noir-ft",
      name: "Neo-Noir",
      weapon: "M4A4",
      category: "rifle",
      rarity: "milspec",
      condition: "FT",
      price: 28.0,
      originalPrice: 28.0,
      discount: 0,
      float: 0.22,
      stattrak: false,
      rating: 3.9,
      description:
         "A noir comic book illustration of a woman in the rain. Dark and cinematic.",
      tags: ["new"],
      inStock: true,
   },
   {
      id: "deagle-golden-koi-fn",
      name: "Golden Koi",
      weapon: "Desert Eagle",
      category: "pistol",
      rarity: "restricted",
      condition: "FN",
      price: 95.0,
      originalPrice: 95.0,
      discount: 0,
      float: 0.03,
      stattrak: false,
      rating: 4.4,
      description:
         "Intricate golden koi fish patterns on a deep black background. Elegant and rare.",
      tags: ["new", "popular"],
      inStock: true,
   },
   {
      id: "ak47-fire-serpent-ft",
      name: "Fire Serpent",
      weapon: "AK-47",
      category: "rifle",
      rarity: "covert",
      condition: "FT",
      price: 180.0,
      originalPrice: 180.0,
      discount: 0,
      float: 0.28,
      stattrak: true,
      rating: 4.5,
      description:
         "A fiery serpent coils around the rifle body in vivid orange and red. A classic drop-era skin.",
      tags: ["popular"],
      inStock: true,
   },
   {
      id: "usps-neo-noir-fn",
      name: "Neo-Noir",
      weapon: "USP-S",
      category: "pistol",
      rarity: "classified",
      condition: "FN",
      price: 48.0,
      originalPrice: 65.0,
      discount: 26,
      float: 0.05,
      stattrak: false,
      rating: 4.0,
      description:
         "Matching the M4A4 series, a dark noir illustration on the silenced pistol.",
      tags: ["on-sale", "new"],
      inStock: true,
   },
   {
      id: "butterfly-fade-fn",
      name: "Fade",
      weapon: "Butterfly Knife",
      category: "knife",
      rarity: "contraband",
      condition: "FN",
      price: 980.0,
      originalPrice: 980.0,
      discount: 0,
      float: 0.009,
      stattrak: false,
      rating: 5.0,
      description:
         "The Butterfly Knife Fade transitions through purple, pink and yellow. One of the most coveted knives in the game.",
      tags: ["featured", "popular"],
      inStock: false,
   },
   {
      id: "gloves-sport-pandora",
      name: "Pandora's Box",
      weapon: "Sport Gloves",
      category: "gloves",
      rarity: "contraband",
      condition: "FT",
      price: 430.0,
      originalPrice: 430.0,
      discount: 0,
      float: 0.16,
      stattrak: false,
      rating: 4.8,
      description:
         "Deep purple and black geometric patterns. The rarest glove skin in CS2.",
      tags: ["popular"],
      inStock: true,
   },
   {
      id: "mp9-wild-lily-fn",
      name: "Wild Lily",
      weapon: "MP9",
      category: "smg",
      rarity: "classified",
      condition: "FN",
      price: 22.0,
      originalPrice: 22.0,
      discount: 0,
      float: 0.07,
      stattrak: false,
      rating: 3.7,
      description:
         "Delicate lily illustrations across the body in soft greens and pinks.",
      tags: ["new"],
      inStock: true,
   },
   {
      id: "awp-medusa-fn",
      name: "Medusa",
      weapon: "AWP",
      category: "sniper",
      rarity: "covert",
      condition: "FN",
      price: 780.0,
      originalPrice: 780.0,
      discount: 0,
      float: 0.03,
      stattrak: false,
      rating: 4.9,
      description:
         "A mythological Medusa illustration across the AWP body. One of the rarest and most detailed skins ever made.",
      tags: ["popular", "featured"],
      inStock: true,
   },
   {
      id: "p250-see-ya-later-fn",
      name: "See Ya Later",
      weapon: "P250",
      category: "pistol",
      rarity: "milspec",
      condition: "FN",
      price: 8.0,
      originalPrice: 12.0,
      discount: 33,
      float: 0.06,
      stattrak: false,
      rating: 3.5,
      description:
         "A cartoon alligator in sunglasses. Lighthearted and bright.",
      tags: ["on-sale", "new"],
      inStock: true,
   },
   {
      id: "mac10-neon-rider-fn",
      name: "Neon Rider",
      weapon: "MAC-10",
      category: "smg",
      rarity: "restricted",
      condition: "FN",
      price: 14.0,
      originalPrice: 14.0,
      discount: 0,
      float: 0.04,
      stattrak: false,
      rating: 3.6,
      description:
         "A synthwave biker across a neon purple and pink body. Retro and vivid.",
      tags: ["new"],
      inStock: true,
   },
];

export const INITIAL_DROPS = [
   {
      id: 1,
      name: "Gloves | Vice",
      wear: "MW",
      price: "$2,400.00",
      img: "/media/images/gloves.avif",
   },
   {
      id: 2,
      name: "Karambit | Doppler",
      wear: "FN",
      price: "$1,120.00",
      img: "/media/images/karambit.avif",
   },
   {
      id: 3,
      name: "AK-47 | Fire Serpent",
      wear: "FT",
      price: "$740.00",
      img: "/media/images/ak.avif",
   },
   {
      id: 4,
      name: "AWP | Dragon Lore",
      wear: "FT",
      price: "$3,200.00",
      img: "/media/images/awp.avif",
   },
];

export const ak47 = [
   {
      id: "ak47-redline-ft",
      name: "Redline",
      weapon: "AK-47",
      category: "rifle",
      rarity: "classified",
      condition: "FT",
      price: 12.5,
      originalPrice: 18.0,
      discount: 30,
      float: 0.24,
      stattrak: false,
      rating: 4.2,
      patternIndex: 419,
      paintSeed: 512,
      collection: "Operation Breakout",
      tradeLock: false,
      listed: "1 hour ago",
      description:
         "The AK-47 Redline is one of the most recognizable and beloved skins.",
      tags: ["featured", "on-sale"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787209386/16.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787209413/16-2.png",
      ],
   },
   {
      id: "ak47-wild-lotus-fn",
      name: "Wild Lotus",
      weapon: "AK-47",
      category: "rifle",
      rarity: "covert",
      condition: "FN",
      price: 540.0,
      originalPrice: 540.0,
      discount: 0,
      float: 0.06,
      stattrak: true,
      rating: 4.7,
      patternIndex: 255,
      paintSeed: 741,
      collection: "CS20 Case",
      tradeLock: false,
      listed: "5 hours ago",
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["popular", "new"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787208747/9.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787208786/9-2.png",
      ],
   },
   {
      id: "ak47-fire-serpent-ft",
      name: "Fire Serpent",
      weapon: "AK-47",
      category: "rifle",
      rarity: "covert",
      condition: "FT",
      price: 180.0,
      originalPrice: 180.0,
      discount: 0,
      float: 0.28,
      stattrak: true,
      rating: 4.5,
      patternIndex: 661,
      paintSeed: 887,
      collection: "Operation Bravo Case",
      tradeLock: false,
      listed: "3 hours ago",
      description:
         "The AK-47 Fire Serpent is one of the oldest, rarest and most legendary skins.",
      tags: ["popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787208839/10.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787208847/10-2.png",
      ],
   },
   {
      id: "ak47-asiimov-fn",
      name: "Asiimov",
      weapon: "AK-47",
      category: "rifle",
      rarity: "covert",
      condition: "FN",
      price: 95.0,
      originalPrice: 120.0,
      discount: 20,
      float: 0.05,
      stattrak: false,
      rating: 4.6,
      patternIndex: 334,
      paintSeed: 623,
      collection: "Chroma Case",
      tradeLock: false,
      listed: "30 minutes ago",
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["on-sale", "popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787208870/11.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787208884/11-2.png",
      ],
   },
   {
      id: "ak47-neon-revolution-fn",
      name: "Neon Revolution",
      weapon: "AK-47",
      category: "rifle",
      rarity: "classified",
      condition: "FN",
      price: 28.0,
      originalPrice: 36.0,
      discount: 22,
      float: 0.04,
      stattrak: false,
      rating: 4.1,
      patternIndex: 178,
      paintSeed: 304,
      collection: "Chroma 2 Case",
      tradeLock: false,
      listed: "7 hours ago",
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["on-sale", "new"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787208919/12.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787209180/12-2.png",
      ],
   },
   {
      id: "ak47-vulcan-fn",
      name: "Vulcan",
      weapon: "AK-47",
      category: "rifle",
      rarity: "covert",
      condition: "FN",
      price: 65.0,
      originalPrice: 65.0,
      discount: 0,
      float: 0.03,
      stattrak: true,
      rating: 4.4,
      patternIndex: 502,
      paintSeed: 198,
      collection: "Operation Vanguard Weapon Case",
      tradeLock: false,
      listed: "2 hours ago",
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787209212/13.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787209233/13-2.png",
      ],
   },
   {
      id: "ak47-bloodsport-fn",
      name: "Bloodsport",
      weapon: "AK-47",
      category: "rifle",
      rarity: "covert",
      condition: "FN",
      price: 42.0,
      originalPrice: 55.0,
      discount: 23,
      float: 0.07,
      stattrak: false,
      rating: 4.3,
      patternIndex: 89,
      paintSeed: 456,
      collection: "Spectrum Case",
      tradeLock: false,
      listed: "4 hours ago",
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["on-sale"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787209263/14.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787209274/14-2.png",
      ],
   },
   {
      id: "ak47-fuel-injector-fn",
      name: "Fuel Injector",
      weapon: "AK-47",
      category: "rifle",
      rarity: "classified",
      condition: "FN",
      price: 18.0,
      originalPrice: 18.0,
      discount: 0,
      float: 0.05,
      stattrak: false,
      rating: 3.9,
      patternIndex: 731,
      paintSeed: 63,
      collection: "Operation Wildfire Case",
      tradeLock: false,
      listed: "6 hours ago",
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["new"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787209327/15.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787209340/15-2.png",
      ],
   },
];

export const knives = [
   {
      id: "karambit-doppler-fn",
      name: "Doppler Phase 4",
      weapon: "Karambit",
      category: "knife",
      rarity: "contraband",
      condition: "FN",
      price: 640.0,
      originalPrice: 640.0,
      discount: 0,
      float: 0.014,
      stattrak: false,
      rating: 4.9,
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["featured", "popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210425/17.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210440/17-2.png",
      ],
   },
   {
      id: "butterfly-fade-fn",
      name: "Fade",
      weapon: "Butterfly Knife",
      category: "knife",
      rarity: "contraband",
      condition: "FN",
      price: 980.0,
      originalPrice: 980.0,
      discount: 0,
      float: 0.009,
      stattrak: false,
      rating: 5.0,
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["featured", "popular"],
      inStock: false,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210467/18.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210485/18-2.png",
      ],
   },
   {
      id: "m9-bayonet-marble-fade-fn",
      name: "Marble Fade",
      weapon: "M9 Bayonet",
      category: "knife",
      rarity: "contraband",
      condition: "FN",
      price: 520.0,
      originalPrice: 520.0,
      discount: 0,
      float: 0.01,
      stattrak: false,
      rating: 4.8,
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210498/19.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210512/19-2.png",
      ],
   },
   {
      id: "karambit-tiger-tooth-fn",
      name: "Tiger Tooth",
      weapon: "Karambit",
      category: "knife",
      rarity: "contraband",
      condition: "FN",
      price: 480.0,
      originalPrice: 480.0,
      discount: 0,
      float: 0.008,
      stattrak: true,
      rating: 4.7,
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210553/20.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210561/20-2.png",
      ],
   },
   {
      id: "flip-knife-doppler-fn",
      name: "Doppler Phase 2",
      weapon: "Flip Knife",
      category: "knife",
      rarity: "contraband",
      condition: "FN",
      price: 280.0,
      originalPrice: 340.0,
      discount: 17,
      float: 0.02,
      stattrak: false,
      rating: 4.5,
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["on-sale"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210587/21.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210636/21-2.png",
      ],
   },
   {
      id: "bayonet-autotronic-ft",
      name: "Autotronic",
      weapon: "Bayonet",
      category: "knife",
      rarity: "contraband",
      condition: "FT",
      price: 210.0,
      originalPrice: 280.0,
      discount: 25,
      float: 0.18,
      stattrak: false,
      rating: 4.2,
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["on-sale"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210685/22.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210695/22-2.png",
      ],
   },
   {
      id: "huntsman-knife-fade-fn",
      name: "Fade",
      weapon: "Huntsman Knife",
      category: "knife",
      rarity: "contraband",
      condition: "FN",
      price: 320.0,
      originalPrice: 320.0,
      discount: 0,
      float: 0.011,
      stattrak: true,
      rating: 4.6,
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210740/23.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210782/23-2.png",
      ],
   },
   {
      id: "shadow-daggers-doppler-fn",
      name: "Doppler Phase 3",
      weapon: "Shadow Daggers",
      category: "knife",
      rarity: "contraband",
      condition: "FN",
      price: 180.0,
      originalPrice: 220.0,
      discount: 18,
      float: 0.03,
      stattrak: false,
      rating: 4.0,
      description:
         "The AK-47 Wild Lotus is widely regarded as one of the most Beautiful Skins.",
      tags: ["on-sale", "new"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210797/24.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787211068/24-2.png",
      ],
   },
];

export const snipers = [
   {
      id: "awp-dragon-lore-fn",
      name: "Dragon Lore",
      weapon: "AWP",
      category: "sniper",
      rarity: "contraband",
      condition: "FN",
      price: 3200.0,
      originalPrice: 3200.0,
      discount: 0,
      float: 0.008,
      stattrak: false,
      rating: 5.0,
      description:
         "The most iconic AWP skin ever made. A golden dragon coils across the body — the holy grail of CS2 skins.",
      tags: ["featured", "popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787211634/25.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787211745/25-2.png",
      ],
   },
   {
      id: "awp-asiimov-fn",
      name: "Asiimov",
      weapon: "AWP",
      category: "sniper",
      rarity: "covert",
      condition: "FN",
      price: 89.0,
      originalPrice: 110.0,
      discount: 19,
      float: 0.08,
      stattrak: true,
      rating: 4.8,
      description:
         "Futuristic orange and white design on a dark body. One of the most recognizable AWP skins.",
      tags: ["featured", "on-sale", "popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787211818/26.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787211828/26-2.png",
      ],
   },
   {
      id: "awp-lightning-strike-fn",
      name: "Lightning Strike",
      weapon: "AWP",
      category: "sniper",
      rarity: "covert",
      condition: "FN",
      price: 220.0,
      originalPrice: 220.0,
      discount: 0,
      float: 0.04,
      stattrak: false,
      rating: 4.6,
      description:
         "Electric yellow lightning bolts streak across a white canvas. Clean and iconic.",
      tags: ["popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787211917/27.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787211974/27-2.png",
      ],
   },
   {
      id: "awp-medusa-fn",
      name: "Medusa",
      weapon: "AWP",
      category: "sniper",
      rarity: "covert",
      condition: "FN",
      price: 780.0,
      originalPrice: 780.0,
      discount: 0,
      float: 0.03,
      stattrak: false,
      rating: 4.9,
      description:
         "A mythological Medusa illustration across the AWP body. One of the rarest and most detailed skins ever made.",
      tags: ["popular", "featured"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787212004/28.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787212166/28-2.png",
      ],
   },
   {
      id: "awp-hyper-beast-fn",
      name: "Hyper Beast",
      weapon: "AWP",
      category: "sniper",
      rarity: "covert",
      condition: "FN",
      price: 95.0,
      originalPrice: 120.0,
      discount: 20,
      float: 0.06,
      stattrak: true,
      rating: 4.5,
      description:
         "Vivid monster artwork splashed across the AWP in pinks, purples and greens.",
      tags: ["on-sale", "popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787212317/30.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787212323/30-2.png",
      ],
   },
   {
      id: "awp-wildfire-fn",
      name: "Wildfire",
      weapon: "AWP",
      category: "sniper",
      rarity: "covert",
      condition: "FN",
      price: 140.0,
      originalPrice: 140.0,
      discount: 0,
      float: 0.02,
      stattrak: false,
      rating: 4.4,
      description:
         "Fiery orange and red flames engulf the AWP body. Bold and aggressive.",
      tags: ["new"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787212366/31.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787212373/31-2.png",
      ],
   },
   {
      id: "ssg08-dragonfire-fn",
      name: "Dragonfire",
      weapon: "SSG 08",
      category: "sniper",
      rarity: "covert",
      condition: "FN",
      price: 45.0,
      originalPrice: 60.0,
      discount: 25,
      float: 0.05,
      stattrak: false,
      rating: 4.1,
      description:
         "A fire-breathing dragon wraps around the SSG 08 scout rifle. Affordable and stunning.",
      tags: ["on-sale", "new"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787212413/32.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787212420/32-2.png",
      ],
   },
   {
      id: "awp-neo-noir-fn",
      name: "Neo-Noir",
      weapon: "AWP",
      category: "sniper",
      rarity: "classified",
      condition: "FN",
      price: 38.0,
      originalPrice: 50.0,
      discount: 24,
      float: 0.07,
      stattrak: true,
      rating: 4.2,
      description:
         "Dark noir comic illustration across the AWP. Mysterious and cinematic.",
      tags: ["on-sale"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787212109/29.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787212066/29-2.png",
      ],
   },
];

export const gloves = [
   {
      id: "sport-gloves-pandoras-box-ft",
      name: "Pandora's Box",
      weapon: "Sport Gloves",
      category: "gloves",
      rarity: "contraband",
      condition: "FT",
      price: 430.0,
      originalPrice: 430.0,
      discount: 0,
      float: 0.16,
      stattrak: false,
      rating: 4.8,
      description:
         "Deep purple and black geometric patterns. The rarest glove skin in CS2.",
      tags: ["popular", "featured"],
      inStock: true,
      image: Gloves1,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206240/playside.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206279/backside.png",
      ],
   },
   {
      id: "sport-gloves-superconductor-ft",
      name: "Superconductor",
      weapon: "Sport Gloves",
      category: "gloves",
      rarity: "contraband",
      condition: "FT",
      price: 380.0,
      originalPrice: 380.0,
      discount: 0,
      float: 0.18,
      stattrak: false,
      rating: 4.7,
      description:
         "Sleek black gloves with a circuit board pattern. Futuristic and clean.",
      tags: ["popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206370/1.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206389/2.png",
      ],
   },
   {
      id: "driver-gloves-king-snake-ft",
      name: "King Snake",
      weapon: "Driver Gloves",
      category: "gloves",
      rarity: "contraband",
      condition: "FT",
      price: 320.0,
      originalPrice: 380.0,
      discount: 15,
      float: 0.2,
      stattrak: false,
      rating: 4.6,
      description:
         "Black leather gloves with a striking snake scale pattern across the back.",
      tags: ["on-sale", "popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206443/3.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206456/3-2.png",
      ],
   },
   {
      id: "moto-gloves-spearmint-ft",
      name: "Spearmint",
      weapon: "Moto Gloves",
      category: "gloves",
      rarity: "contraband",
      condition: "FT",
      price: 290.0,
      originalPrice: 290.0,
      discount: 0,
      float: 0.15,
      stattrak: false,
      rating: 4.5,
      description:
         "Fresh mint green moto gloves with a worn leather look. Clean and rare.",
      tags: ["popular"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206501/4.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206516/4-2.png",
      ],
   },
   {
      id: "hand-wraps-cobalt-skulls-ft",
      name: "Cobalt Skulls",
      weapon: "Hand Wraps",
      category: "gloves",
      rarity: "contraband",
      condition: "FT",
      price: 260.0,
      originalPrice: 320.0,
      discount: 18,
      float: 0.22,
      stattrak: false,
      rating: 4.4,
      description:
         "Deep blue hand wraps with a skull pattern. Dark and intimidating.",
      tags: ["on-sale"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206579/5.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206597/5-2.png",
      ],
   },
   {
      id: "bloodhound-gloves-charred-ft",
      name: "Charred",
      weapon: "Bloodhound Gloves",
      category: "gloves",
      rarity: "contraband",
      condition: "FT",
      price: 210.0,
      originalPrice: 210.0,
      discount: 0,
      float: 0.19,
      stattrak: false,
      rating: 4.3,
      description:
         "Burnt black tactical gloves with a charred texture. Rugged and aggressive.",
      tags: ["new"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206649/6.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206668/6-2.png",
      ],
   },
   {
      id: "driver-gloves-lunar-weave-ft",
      name: "Lunar Weave",
      weapon: "Driver Gloves",
      category: "gloves",
      rarity: "contraband",
      condition: "FT",
      price: 180.0,
      originalPrice: 220.0,
      discount: 18,
      float: 0.24,
      stattrak: false,
      rating: 4.1,
      description:
         "Dark navy blue driver gloves with a subtle woven pattern. Elegant and understated.",
      tags: ["on-sale", "new"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206727/7.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206743/7-2.png",
      ],
   },
   {
      id: "moto-gloves-eclipse-ft",
      name: "Eclipse",
      weapon: "Moto Gloves",
      category: "gloves",
      rarity: "contraband",
      condition: "FT",
      price: 150.0,
      originalPrice: 190.0,
      discount: 21,
      float: 0.21,
      stattrak: false,
      rating: 4.0,
      description:
         "Black moto gloves with dark eclipse pattern. Minimal and stealthy.",
      tags: ["on-sale"],
      inStock: true,
      image: [
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206787/8.png",
         "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206798/8-2.png",
      ],
   },
];

// ── Categories ─────────────────────────────
export const categories = [
   { id: "all", label: "All skins" },
   { id: "rifle", label: "Rifles" },
   { id: "pistol", label: "Pistols" },
   { id: "knife", label: "Knives" },
   { id: "sniper", label: "Snipers" },
   { id: "smg", label: "SMGs" },
   { id: "gloves", label: "Gloves" },
];

// ── Rarities ───────────────────────────────
export const rarities = [
   { id: "contraband", label: "Contraband", color: "#ff4500" },
   { id: "covert", label: "Covert", color: "#ff0000" },
   { id: "classified", label: "Classified", color: "#cc00ff" },
   { id: "restricted", label: "Restricted", color: "#4400ff" },
   { id: "milspec", label: "Mil-Spec", color: "#0066ff" },
   { id: "industrial", label: "Industrial", color: "#00ccff" },
   { id: "consumer", label: "Consumer Grade", color: "#888888" },
];

// ── Conditions ─────────────────────────────
export const conditions = [
   { id: "FN", label: "Factory New", floatRange: [0.0, 0.07] },
   { id: "MW", label: "Minimal Wear", floatRange: [0.07, 0.15] },
   { id: "FT", label: "Field-Tested", floatRange: [0.15, 0.38] },
   { id: "WW", label: "Well-Worn", floatRange: [0.38, 0.45] },
   { id: "BS", label: "Battle-Scarred", floatRange: [0.45, 1.0] },
];

// -- Why Us Features
export const FEATURES = [
   {
      id: 1,
      title: "Instant Skin Delivery",
      description:
         "Skins land in your Steam inventory within minutes of purchase. No waiting, no delays — just instant transfers through Steam's official trade system.",
      tag: "DELIVERY",
      date: "Avg. 3 minutes",
      featured: true,
      image: ArticleImg2,
   },
   {
      id: 2,
      title: "Fees As Low As 2%",
      description:
         "We track market prices 24/7 and guarantee the lowest fees in the market. Keep more of your money on every trade.",
      tag: "PRICING",
      date: "Industry lowest",
      featured: false,
      image: ArticleImg,
   },
   {
      id: 3,
      title: "100% Secure Trades",
      description:
         "Every transaction uses Steam's official trade system. Your account and inventory are always protected — zero incidents since launch.",
      tag: "SECURITY",
      date: "0 incidents",
      featured: false,
      image: ArticleImg3,
   },
];

// ── Nav Headers ────────────────────────────
export const NavHeaders = [
   { id: 1, label: "Home", path: "/" },
   { id: 2, label: "Store", path: "/store" },
   { id: 4, label: "Orders", path: "/orders" },
   // { id: 4, label: "Contact Us", path: "" },
];

// --Footer Links ------
export const FooterQuickLinks = [
   { label: "Browse Market", href: "/store", key: 1 },
   { label: "Sell Skins", href: "/store", key: 2 },
   { label: "Support", href: "/store", key: 3 },
];

export const FooterLegalLinks = [
   { label: "Privacy Policy", href: "/privacy" },
   { label: "Terms of Service", href: "/terms" },
   // { label: "Cookie Policy", href: "/cookies" },
   { label: "About Us", href: "/about" },
];

export const FooterStatsLinks = [
   { value: "$2.4M", label: "Traded" },
   { value: "4.6M+", label: "Users" },
   { value: "12K", label: "Today" },
];

export const FooterCategories = [
   { value: "Rifles", href: "/rifle" },
   { value: "Knives", href: "/knife" },
   { value: "Gloves", href: "/gloves" },
   { value: "Snipers", href: "/sniper" },
];

export const allSkins = [...ak47, ...knives, ...snipers, ...gloves];

// ── Payment Methods ───────────────────────────
export const PAYMENT_METHODS = [
   {
      id: "card",
      label: "Credit Card",
      sub: "Visa, Mastercard, Amex",
      icon: "creaditCardIcon",
   },
   { id: "paypal", label: "PayPal", sub: "Fast & Secure", icon: "walletIcon" },
];

// ── Payment Perks ───────────────────────────
export const PAYMENT_PERKS = [
   {
      label: "VERIFIED SELLERS",
      desc: "Every listing is checked for authenticity before it goes live.",
   },
   {
      label: "INSTANT DELIVERY",
      desc: "Skins land in your Steam inventory within minutes of payment.",
   },
   {
      label: "7-DAY RETURNS",
      desc: "Full refund if a skin doesn't match its listing.",
   },
   {
      label: "24/7 SUPPORT",
      desc: "Real humans, average reply time under 5 minutes.",
   },
];

// ── Payment Description───────────────────────────
export const PAYMENT_DESCRIPTIONS = {
   card: `Your card details are encrypted with 256-bit SSL and never stored on our servers. Payment is processed instantly through our secure gateway — skins are delivered to your Steam inventory within minutes of authorization. We support Visa, Mastercard, and American Express with no additional processing fee. All transactions are protected by 3D Secure authentication, and you'll receive an instant confirmation email with a transaction reference once your payment clears.`,

   crypto: `Send the exact amount shown to the wallet address above — partial payments will not be accepted. Transactions are verified after 3 network confirmations, typically taking 10 to 15 minutes depending on network congestion. We support BTC, ETH, and USDT on ERC-20 — ensure you're sending on the correct chain to avoid unrecoverable loss of funds. The wallet address is unique to this session and expires after 15 minutes of inactivity.`,

   paypal: `Clicking Place Order will redirect you to PayPal's secure checkout — no PayPal account required, guest checkout is supported. Once payment is confirmed, skins are pushed to your Steam inventory within minutes. A standard PayPal fee of 2.9% + $0.30 applies and is not retained by SkinVault. PayPal Buyer Protection covers all eligible transactions in the event of a dispute.`,
};

// ── Auth Points ───────────────────────────
export const POINTS = [
   {
      label: "Instant Trading",
      desc: "Buy, sell and exchange CS2 skins in seconds.",
   },
   { label: "Lowest Fees", desc: "Market fees starting from just 1.5%." },
   { label: "Secure Payouts", desc: "40+ withdrawal methods, always safe." },
   { label: "Best Prices", desc: "Up to 60% off Steam market prices." },
];

export const filters = {
   categories: [
      { id: "all", label: "All" },
      { id: "knife", label: "Knives" },
      { id: "rifle", label: "Rifles" },
      { id: "sniper", label: "Snipers" },
      { id: "gloves", label: "Gloves" },
      { id: "pistol", label: "Pistols" },
      { id: "smg", label: "SMGs" },
   ],

   conditions: [
      { id: "FN", label: "Factory New" },
      { id: "MW", label: "Minimal Wear" },
      { id: "FT", label: "Field-Tested" },
      { id: "WW", label: "Well-Worn" },
      { id: "BS", label: "Battle-Scarred" },
   ],

   priceRange: {
      min: 0,
      max: 1000,
   },
};

export const PROMO_CODES = {
   VAULT10: { id: 1, discount: 10 },
   SKIN20: { id: 2, discount: 20 },
   CS2WIN: { id: 3, discount: 15 },
};

export const STATIC_ORDERS = [
   {
      id: "SV-1788601363130",
      items: [
         {
            id: "sport-gloves-superconductor-ft",
            name: "Superconductor",
            weapon: "Sport Gloves",
            condition: "FT",
            price: 380,
            quantity: 4,
            rarity: "contraband",
            float: 0.18,
            image: [
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206370/1.png",
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206389/2.png",
            ],
         },
      ],
      total: 1520,
      placedAt: "2026-09-05T09:42:43.130Z",
      status: "delivering",
   },
   {
      id: "SV-1788601753307",
      items: [
         {
            id: "sport-gloves-superconductor-ft",
            name: "Superconductor",
            weapon: "Sport Gloves",
            condition: "FT",
            price: 380,
            quantity: 2,
            rarity: "contraband",
            float: 0.18,
            image: [
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206370/1.png",
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206389/2.png",
            ],
         },
         {
            id: "moto-gloves-spearmint-ft",
            name: "Spearmint",
            weapon: "Moto Gloves",
            condition: "FT",
            price: 290,
            quantity: 2,
            rarity: "contraband",
            float: 0.15,
            image: [
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206501/4.png",
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787206516/4-2.png",
            ],
         },
      ],
      total: 1860,
      placedAt: "2026-09-05T09:49:13.307Z",
      status: "delivering",
   },
   {
      id: "SV-1788784392954",
      items: [
         {
            id: "m9-bayonet-marble-fade-fn",
            name: "Marble Fade",
            weapon: "M9 Bayonet",
            condition: "FN",
            price: 520,
            quantity: 7,
            rarity: "contraband",
            float: 0.01,
            image: [
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210498/19.png",
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210512/19-2.png",
            ],
         },
         {
            id: "karambit-doppler-fn",
            name: "Doppler Phase 4",
            weapon: "Karambit",
            condition: "FN",
            price: 640,
            quantity: 5,
            rarity: "contraband",
            float: 0.014,
            image: [
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210425/17.png",
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210440/17-2.png",
            ],
         },
      ],
      total: 13080,
      placedAt: "2026-09-07T12:33:12.954Z",
      status: "delivering",
   },
];

export const MOCK_ORDERS = [
   {
      id: "ORD-8F3K-99RT",
      items: [
         {
            name: "AK-47",
            image: [
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787209386/16.png",
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787209413/16-2.png",
            ],
         },
         {
            name: "AWP",
            image: [
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787211634/25.png",
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787211745/25-2.png",
            ],
         },
         {
            name: "Karambit",
            image: [
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210425/17.png",
               "https://res.cloudinary.com/wos7zsyn/image/upload/v1787210440/17-2.png",
            ],
         },
      ],
      extraCount: 1,
      itemNames: "AK-47, AWP, Karambit",
      date: "Sep 5, 2026",
      total: 1224.89,
      status: "delivered",
   },
   {
      id: "ORD-2L91-KX07",
      items: [
         { name: "M4A4", image: null },
         { name: "Glock-18", image: null },
      ],
      extraCount: 0,
      itemNames: "M4A4, Glock-18",
      date: "Aug 29, 2026",
      total: 312.4,
      status: "delivering",
   },
   {
      id: "ORD-9RZP-A44M",
      items: [{ name: "Butterfly Knife", image: null }],
      extraCount: 0,
      itemNames: "Butterfly Knife | Fade",
      date: "Aug 21, 2026",
      total: 1640.0,
      status: "delivered",
   },
   {
      id: "ORD-4TQW-B71C",
      items: [
         { name: "Sport Gloves", image: null },
         { name: "USP-S", image: null },
      ],
      extraCount: 2,
      itemNames: "Sport Gloves, USP-S",
      date: "Aug 12, 2026",
      total: 2980.15,
      status: "delivered",
   },
   {
      id: "ORD-1MXE-773D",
      items: [{ name: "Desert Eagle", image: null }],
      extraCount: 0,
      itemNames: "Desert Eagle | Blaze",
      date: "Jul 30, 2026",
      total: 96.0,
      status: "refunded",
   },
];
